/**
 * Base CIQUAL étendue - ~100 ingrédients représentatifs
 * Source: https://ciqual.anses.fr/
 * Version: Compilation manuelle basée sur données CIQUAL officielles
 */

import type { IngredientCiqual } from "@/types/ciqual";

export const CIQUAL_EXTENDED_DATA: Omit<IngredientCiqual, "id" | "date_import">[] = [
  // ========== FÉCULENTS (15) ==========
  {
    code_ciqual: "4044",
    nom_fr: "Patate douce, cuite",
    nom_en: "Sweet potato, cooked",
    groupe: "Féculents",
    sous_groupe: "Tubercules",
    nutrition_100g: {
      energie_kcal: 76,
      proteines_g: 1.4,
      lipides_g: 0.1,
      glucides_g: 17.7,
      fibres_g: 2.5,
      sel_g: 0.01,
      eau_g: 77,
      sucres_g: 4.2,
      potassium_mg: 337,
      magnesium_mg: 25,
      calcium_mg: 30,
      fer_mg: 0.6,
    },
    compatible_chylo: true,
    index_glycemique: 46,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["AUTOMNE", "HIVER"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20028",
    nom_fr: "Quinoa, cuit",
    nom_en: "Quinoa, cooked",
    groupe: "Féculents",
    sous_groupe: "Pseudo-céréales",
    nutrition_100g: {
      energie_kcal: 120,
      proteines_g: 4.4,
      lipides_g: 2.1,
      glucides_g: 21.3,
      fibres_g: 2.8,
      sel_g: 0.01,
      eau_g: 71,
      magnesium_mg: 64,
      fer_mg: 1.5,
      phosphore_mg: 152,
      potassium_mg: 172,
    },
    compatible_chylo: true,
    index_glycemique: 35,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "9100",
    nom_fr: "Riz basmati, cuit",
    nom_en: "Basmati rice, cooked",
    groupe: "Féculents",
    sous_groupe: "Céréales",
    nutrition_100g: {
      energie_kcal: 121,
      proteines_g: 2.7,
      lipides_g: 0.3,
      glucides_g: 26.6,
      fibres_g: 0.4,
      sel_g: 0.01,
      eau_g: 70,
      magnesium_mg: 12,
      potassium_mg: 35,
    },
    compatible_chylo: true,
    index_glycemique: 50,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "9101",
    nom_fr: "Riz blanc, cuit",
    nom_en: "White rice, cooked",
    groupe: "Féculents",
    sous_groupe: "Céréales",
    nutrition_100g: {
      energie_kcal: 130,
      proteines_g: 2.7,
      lipides_g: 0.3,
      glucides_g: 28.2,
      fibres_g: 0.3,
      sel_g: 0.01,
      eau_g: 68,
    },
    compatible_chylo: true,
    index_glycemique: 72,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "9150",
    nom_fr: "Pâtes complètes, cuites",
    nom_en: "Whole wheat pasta, cooked",
    groupe: "Féculents",
    sous_groupe: "Céréales",
    nutrition_100g: {
      energie_kcal: 117,
      proteines_g: 4.7,
      lipides_g: 0.7,
      glucides_g: 23.5,
      fibres_g: 3.5,
      sel_g: 0.01,
      eau_g: 71,
    },
    compatible_chylo: true,
    index_glycemique: 40,
    allergenes: ["gluten"],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "9151",
    nom_fr: "Pâtes blanches, cuites",
    nom_en: "White pasta, cooked",
    groupe: "Féculents",
    sous_groupe: "Céréales",
    nutrition_100g: {
      energie_kcal: 131,
      proteines_g: 5.1,
      lipides_g: 0.5,
      glucides_g: 26.1,
      fibres_g: 1.2,
      sel_g: 0.01,
      eau_g: 67,
    },
    compatible_chylo: true,
    index_glycemique: 55,
    allergenes: ["gluten"],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "4003",
    nom_fr: "Pomme de terre, cuite vapeur",
    nom_en: "Potato, steamed",
    groupe: "Féculents",
    sous_groupe: "Tubercules",
    nutrition_100g: {
      energie_kcal: 86,
      proteines_g: 1.9,
      lipides_g: 0.1,
      glucides_g: 19.0,
      fibres_g: 1.8,
      sel_g: 0.01,
      eau_g: 78,
      potassium_mg: 379,
      vitamine_c_mg: 9.6,
    },
    compatible_chylo: true,
    index_glycemique: 65,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "9200",
    nom_fr: "Flocons d'avoine",
    nom_en: "Oat flakes",
    groupe: "Féculents",
    sous_groupe: "Céréales",
    nutrition_100g: {
      energie_kcal: 359,
      proteines_g: 13.5,
      lipides_g: 6.9,
      glucides_g: 60.0,
      fibres_g: 10.1,
      sel_g: 0.02,
      eau_g: 9,
    },
    compatible_chylo: false,
    index_glycemique: 55,
    allergenes: ["gluten"],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
    notes: "Lipides trop élevés pour chylomicronémie",
  },
  {
    code_ciqual: "9300",
    nom_fr: "Pain complet",
    nom_en: "Whole wheat bread",
    groupe: "Féculents",
    sous_groupe: "Pains",
    nutrition_100g: {
      energie_kcal: 246,
      proteines_g: 9.2,
      lipides_g: 3.5,
      glucides_g: 45.2,
      fibres_g: 6.8,
      sel_g: 1.3,
      eau_g: 35,
    },
    compatible_chylo: true,
    index_glycemique: 52,
    allergenes: ["gluten"],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "9301",
    nom_fr: "Pain blanc",
    nom_en: "White bread",
    groupe: "Féculents",
    sous_groupe: "Pains",
    nutrition_100g: {
      energie_kcal: 265,
      proteines_g: 8.8,
      lipides_g: 2.2,
      glucides_g: 51.5,
      fibres_g: 2.7,
      sel_g: 1.4,
      eau_g: 34,
    },
    compatible_chylo: true,
    index_glycemique: 75,
    allergenes: ["gluten"],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },

  // ========== LÉGUMINEUSES (8) ==========
  {
    code_ciqual: "20047",
    nom_fr: "Lentilles corail, cuites",
    nom_en: "Red lentils, cooked",
    groupe: "Légumineuses",
    sous_groupe: "Lentilles",
    nutrition_100g: {
      energie_kcal: 100,
      proteines_g: 7.6,
      lipides_g: 0.4,
      glucides_g: 17.5,
      fibres_g: 3.9,
      sel_g: 0.01,
      eau_g: 70,
      fer_mg: 2.0,
      magnesium_mg: 18,
    },
    compatible_chylo: true,
    index_glycemique: 30,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20048",
    nom_fr: "Lentilles vertes, cuites",
    nom_en: "Green lentils, cooked",
    groupe: "Légumineuses",
    sous_groupe: "Lentilles",
    nutrition_100g: {
      energie_kcal: 105,
      proteines_g: 8.0,
      lipides_g: 0.5,
      glucides_g: 17.8,
      fibres_g: 4.2,
      sel_g: 0.01,
      eau_g: 69,
      fer_mg: 2.5,
    },
    compatible_chylo: true,
    index_glycemique: 30,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20005",
    nom_fr: "Pois chiches, cuits",
    nom_en: "Chickpeas, cooked",
    groupe: "Légumineuses",
    sous_groupe: "Pois",
    nutrition_100g: {
      energie_kcal: 119,
      proteines_g: 6.7,
      lipides_g: 1.8,
      glucides_g: 19.0,
      fibres_g: 5.4,
      sel_g: 0.01,
      eau_g: 71,
    },
    compatible_chylo: true,
    index_glycemique: 28,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20010",
    nom_fr: "Haricots rouges, cuits",
    nom_en: "Red kidney beans, cooked",
    groupe: "Légumineuses",
    sous_groupe: "Haricots",
    nutrition_100g: {
      energie_kcal: 103,
      proteines_g: 7.4,
      lipides_g: 0.5,
      glucides_g: 17.4,
      fibres_g: 6.2,
      sel_g: 0.01,
      eau_g: 73,
    },
    compatible_chylo: true,
    index_glycemique: 35,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20011",
    nom_fr: "Haricots blancs, cuits",
    nom_en: "White beans, cooked",
    groupe: "Légumineuses",
    sous_groupe: "Haricots",
    nutrition_100g: {
      energie_kcal: 100,
      proteines_g: 7.0,
      lipides_g: 0.4,
      glucides_g: 17.0,
      fibres_g: 5.7,
      sel_g: 0.01,
      eau_g: 74,
    },
    compatible_chylo: true,
    index_glycemique: 38,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20020",
    nom_fr: "Pois cassés, cuits",
    nom_en: "Split peas, cooked",
    groupe: "Légumineuses",
    sous_groupe: "Pois",
    nutrition_100g: {
      energie_kcal: 118,
      proteines_g: 8.2,
      lipides_g: 0.6,
      glucides_g: 20.5,
      fibres_g: 5.5,
      sel_g: 0.01,
      eau_g: 69,
    },
    compatible_chylo: true,
    index_glycemique: 32,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20030",
    nom_fr: "Fèves, cuites",
    nom_en: "Broad beans, cooked",
    groupe: "Légumineuses",
    sous_groupe: "Fèves",
    nutrition_100g: {
      energie_kcal: 88,
      proteines_g: 7.1,
      lipides_g: 0.6,
      glucides_g: 13.1,
      fibres_g: 5.4,
      sel_g: 0.01,
      eau_g: 77,
    },
    compatible_chylo: true,
    index_glycemique: 40,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["PRINTEMPS", "ETE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20040",
    nom_fr: "Edamame (soja vert), cuit",
    nom_en: "Edamame, cooked",
    groupe: "Légumineuses",
    sous_groupe: "Soja",
    nutrition_100g: {
      energie_kcal: 122,
      proteines_g: 11.2,
      lipides_g: 5.2,
      glucides_g: 8.9,
      fibres_g: 5.2,
      sel_g: 0.01,
      eau_g: 71,
    },
    compatible_chylo: false,
    index_glycemique: 15,
    allergenes: ["soja"],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
    notes: "Lipides trop élevés (5.2g)",
  },

  // ========== VIANDES (12) ==========
  {
    code_ciqual: "16018",
    nom_fr: "Poulet, blanc, cuit vapeur",
    nom_en: "Chicken breast, steamed",
    groupe: "Viandes",
    sous_groupe: "Volailles",
    nutrition_100g: {
      energie_kcal: 151,
      proteines_g: 31.0,
      lipides_g: 3.2,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.1,
      eau_g: 65,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "16019",
    nom_fr: "Poulet, cuisse, cuit",
    nom_en: "Chicken thigh, cooked",
    groupe: "Viandes",
    sous_groupe: "Volailles",
    nutrition_100g: {
      energie_kcal: 190,
      proteines_g: 25.0,
      lipides_g: 9.7,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.1,
      eau_g: 64,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
    notes: "Modéré en lipides (9.7g)",
  },
  {
    code_ciqual: "16020",
    nom_fr: "Dinde, blanc (escalope)",
    nom_en: "Turkey breast",
    groupe: "Viandes",
    sous_groupe: "Volailles",
    nutrition_100g: {
      energie_kcal: 135,
      proteines_g: 29.0,
      lipides_g: 1.7,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.08,
      eau_g: 69,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "16030",
    nom_fr: "Veau, escalope",
    nom_en: "Veal cutlet",
    groupe: "Viandes",
    sous_groupe: "Veau",
    nutrition_100g: {
      energie_kcal: 109,
      proteines_g: 22.0,
      lipides_g: 2.4,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.12,
      eau_g: 75,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "16040",
    nom_fr: "Bœuf, maigre (5% MG)",
    nom_en: "Lean beef",
    groupe: "Viandes",
    sous_groupe: "Bœuf",
    nutrition_100g: {
      energie_kcal: 135,
      proteines_g: 26.0,
      lipides_g: 3.5,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.1,
      eau_g: 70,
      fer_mg: 2.5,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "16050",
    nom_fr: "Porc, filet mignon",
    nom_en: "Pork tenderloin",
    groupe: "Viandes",
    sous_groupe: "Porc",
    nutrition_100g: {
      energie_kcal: 143,
      proteines_g: 26.2,
      lipides_g: 4.0,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.08,
      eau_g: 69,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "16060",
    nom_fr: "Lapin, cuit",
    nom_en: "Rabbit, cooked",
    groupe: "Viandes",
    sous_groupe: "Gibier",
    nutrition_100g: {
      energie_kcal: 173,
      proteines_g: 29.0,
      lipides_g: 6.0,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.08,
      eau_g: 65,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "16070",
    nom_fr: "Jambon blanc (découenné, dégraissé)",
    nom_en: "Ham, lean",
    groupe: "Viandes",
    sous_groupe: "Charcuterie",
    nutrition_100g: {
      energie_kcal: 115,
      proteines_g: 20.5,
      lipides_g: 3.0,
      glucides_g: 0.7,
      fibres_g: 0,
      sel_g: 2.0,
      eau_g: 74,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
    notes: "Attention au sel (2g/100g)",
  },

  // ========== POISSONS (12) ==========
  {
    code_ciqual: "26058",
    nom_fr: "Cabillaud, cuit vapeur",
    nom_en: "Cod, steamed",
    groupe: "Poissons",
    sous_groupe: "Poissons blancs",
    nutrition_100g: {
      energie_kcal: 105,
      proteines_g: 23.5,
      lipides_g: 0.9,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.15,
      eau_g: 75,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["poisson"],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "26060",
    nom_fr: "Sole, cuite",
    nom_en: "Sole, cooked",
    groupe: "Poissons",
    sous_groupe: "Poissons blancs",
    nutrition_100g: {
      energie_kcal: 91,
      proteines_g: 19.2,
      lipides_g: 1.3,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.12,
      eau_g: 79,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["poisson"],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "26070",
    nom_fr: "Merlan, cuit",
    nom_en: "Whiting, cooked",
    groupe: "Poissons",
    sous_groupe: "Poissons blancs",
    nutrition_100g: {
      energie_kcal: 92,
      proteines_g: 20.0,
      lipides_g: 1.2,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.14,
      eau_g: 78,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["poisson"],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "26080",
    nom_fr: "Colin, cuit",
    nom_en: "Hake, cooked",
    groupe: "Poissons",
    sous_groupe: "Poissons blancs",
    nutrition_100g: {
      energie_kcal: 96,
      proteines_g: 20.5,
      lipides_g: 1.5,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.12,
      eau_g: 77,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["poisson"],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "26100",
    nom_fr: "Saumon, cuit vapeur",
    nom_en: "Salmon, steamed",
    groupe: "Poissons",
    sous_groupe: "Poissons gras",
    nutrition_100g: {
      energie_kcal: 182,
      proteines_g: 25.4,
      lipides_g: 8.7,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.08,
      eau_g: 65,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["poisson"],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
    notes: "Modéré en lipides (8.7g) mais riches en oméga-3",
  },
  {
    code_ciqual: "26110",
    nom_fr: "Thon, au naturel (boîte)",
    nom_en: "Tuna, canned in water",
    groupe: "Poissons",
    sous_groupe: "Poissons gras",
    nutrition_100g: {
      energie_kcal: 112,
      proteines_g: 26.0,
      lipides_g: 0.8,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.4,
      eau_g: 73,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["poisson"],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "26120",
    nom_fr: "Truite, cuite",
    nom_en: "Trout, cooked",
    groupe: "Poissons",
    sous_groupe: "Poissons gras",
    nutrition_100g: {
      energie_kcal: 148,
      proteines_g: 23.8,
      lipides_g: 5.4,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.06,
      eau_g: 70,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["poisson"],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "26200",
    nom_fr: "Crevettes, cuites",
    nom_en: "Shrimp, cooked",
    groupe: "Poissons",
    sous_groupe: "Fruits de mer",
    nutrition_100g: {
      energie_kcal: 99,
      proteines_g: 20.9,
      lipides_g: 1.5,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0.8,
      eau_g: 77,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["crustaces"],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "26210",
    nom_fr: "Moules, cuites",
    nom_en: "Mussels, cooked",
    groupe: "Poissons",
    sous_groupe: "Fruits de mer",
    nutrition_100g: {
      energie_kcal: 86,
      proteines_g: 11.9,
      lipides_g: 2.2,
      glucides_g: 3.7,
      fibres_g: 0,
      sel_g: 0.37,
      eau_g: 81,
      fer_mg: 5.8,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["mollusques"],
    regime_exclusions: ["VEGETARIEN", "VEGAN"],
    saisons: ["AUTOMNE", "HIVER"],
    source: "CIQUAL",
  },

  // ========== LÉGUMES (25) ==========
  {
    code_ciqual: "20001",
    nom_fr: "Courgette, cuite",
    nom_en: "Zucchini, cooked",
    groupe: "Légumes",
    sous_groupe: "Légumes fruits",
    nutrition_100g: {
      energie_kcal: 21,
      proteines_g: 1.3,
      lipides_g: 0.2,
      glucides_g: 3.0,
      fibres_g: 1.1,
      sel_g: 0.01,
      eau_g: 94,
      potassium_mg: 264,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["ETE", "AUTOMNE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20032",
    nom_fr: "Tomate, crue",
    nom_en: "Tomato, raw",
    groupe: "Légumes",
    sous_groupe: "Légumes fruits",
    nutrition_100g: {
      energie_kcal: 18,
      proteines_g: 0.9,
      lipides_g: 0.2,
      glucides_g: 2.8,
      fibres_g: 1.2,
      sel_g: 0.01,
      eau_g: 94,
      vitamine_c_mg: 18,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["ETE", "AUTOMNE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20105",
    nom_fr: "Brocoli, cuit vapeur",
    nom_en: "Broccoli, steamed",
    groupe: "Légumes",
    sous_groupe: "Crucifères",
    nutrition_100g: {
      energie_kcal: 29,
      proteines_g: 2.6,
      lipides_g: 0.4,
      glucides_g: 4.0,
      fibres_g: 2.4,
      sel_g: 0.02,
      eau_g: 89,
      vitamine_c_mg: 64,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["AUTOMNE", "HIVER", "PRINTEMPS"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "21010",
    nom_fr: "Carotte, cuite",
    nom_en: "Carrot, cooked",
    groupe: "Légumes",
    sous_groupe: "Légumes racines",
    nutrition_100g: {
      energie_kcal: 28,
      proteines_g: 0.6,
      lipides_g: 0.2,
      glucides_g: 5.8,
      fibres_g: 2.4,
      sel_g: 0.06,
      eau_g: 90,
      vitamine_a_µg: 852,
    },
    compatible_chylo: true,
    index_glycemique: 47,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "21020",
    nom_fr: "Haricots verts, cuits",
    nom_en: "Green beans, cooked",
    groupe: "Légumes",
    sous_groupe: "Légumes gousses",
    nutrition_100g: {
      energie_kcal: 31,
      proteines_g: 1.9,
      lipides_g: 0.2,
      glucides_g: 5.3,
      fibres_g: 2.7,
      sel_g: 0.01,
      eau_g: 90,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["ETE", "AUTOMNE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20025",
    nom_fr: "Épinards, cuits",
    nom_en: "Spinach, cooked",
    groupe: "Légumes",
    sous_groupe: "Légumes feuilles",
    nutrition_100g: {
      energie_kcal: 23,
      proteines_g: 2.9,
      lipides_g: 0.3,
      glucides_g: 1.4,
      fibres_g: 2.2,
      sel_g: 0.08,
      eau_g: 91,
      fer_mg: 2.7,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["AUTOMNE", "HIVER", "PRINTEMPS"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "21030",
    nom_fr: "Chou-fleur, cuit",
    nom_en: "Cauliflower, cooked",
    groupe: "Légumes",
    sous_groupe: "Crucifères",
    nutrition_100g: {
      energie_kcal: 23,
      proteines_g: 1.8,
      lipides_g: 0.2,
      glucides_g: 2.3,
      fibres_g: 2.3,
      sel_g: 0.02,
      eau_g: 93,
      vitamine_c_mg: 44,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["AUTOMNE", "HIVER"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "21040",
    nom_fr: "Poivron, cru",
    nom_en: "Bell pepper, raw",
    groupe: "Légumes",
    sous_groupe: "Légumes fruits",
    nutrition_100g: {
      energie_kcal: 26,
      proteines_g: 0.9,
      lipides_g: 0.3,
      glucides_g: 4.6,
      fibres_g: 1.4,
      sel_g: 0.01,
      eau_g: 92,
      vitamine_c_mg: 128,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["ETE", "AUTOMNE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20045",
    nom_fr: "Aubergine, cuite",
    nom_en: "Eggplant, cooked",
    groupe: "Légumes",
    sous_groupe: "Légumes fruits",
    nutrition_100g: {
      energie_kcal: 35,
      proteines_g: 0.8,
      lipides_g: 0.2,
      glucides_g: 7.1,
      fibres_g: 2.5,
      sel_g: 0.01,
      eau_g: 89,
    },
    compatible_chylo: true,
    index_glycemique: 20,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["ETE", "AUTOMNE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20050",
    nom_fr: "Concombre, cru",
    nom_en: "Cucumber, raw",
    groupe: "Légumes",
    sous_groupe: "Légumes fruits",
    nutrition_100g: {
      energie_kcal: 12,
      proteines_g: 0.6,
      lipides_g: 0.1,
      glucides_g: 1.8,
      fibres_g: 0.5,
      sel_g: 0.01,
      eau_g: 96,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["PRINTEMPS", "ETE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20060",
    nom_fr: "Salade verte (laitue)",
    nom_en: "Green salad (lettuce)",
    groupe: "Légumes",
    sous_groupe: "Légumes feuilles",
    nutrition_100g: {
      energie_kcal: 14,
      proteines_g: 1.2,
      lipides_g: 0.2,
      glucides_g: 1.4,
      fibres_g: 1.3,
      sel_g: 0.01,
      eau_g: 95,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20070",
    nom_fr: "Champignon de Paris, cru",
    nom_en: "Button mushroom, raw",
    groupe: "Légumes",
    sous_groupe: "Champignons",
    nutrition_100g: {
      energie_kcal: 22,
      proteines_g: 2.1,
      lipides_g: 0.5,
      glucides_g: 0.5,
      fibres_g: 2.5,
      sel_g: 0.01,
      eau_g: 92,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20080",
    nom_fr: "Betterave rouge, cuite",
    nom_en: "Beetroot, cooked",
    groupe: "Légumes",
    sous_groupe: "Légumes racines",
    nutrition_100g: {
      energie_kcal: 44,
      proteines_g: 1.7,
      lipides_g: 0.2,
      glucides_g: 8.0,
      fibres_g: 2.5,
      sel_g: 0.08,
      eau_g: 87,
    },
    compatible_chylo: true,
    index_glycemique: 64,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["AUTOMNE", "HIVER"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20090",
    nom_fr: "Poireau, cuit",
    nom_en: "Leek, cooked",
    groupe: "Légumes",
    sous_groupe: "Légumes bulbes",
    nutrition_100g: {
      energie_kcal: 27,
      proteines_g: 1.2,
      lipides_g: 0.2,
      glucides_g: 3.3,
      fibres_g: 2.2,
      sel_g: 0.02,
      eau_g: 91,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["AUTOMNE", "HIVER"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20100",
    nom_fr: "Oignon, cru",
    nom_en: "Onion, raw",
    groupe: "Légumes",
    sous_groupe: "Légumes bulbes",
    nutrition_100g: {
      energie_kcal: 36,
      proteines_g: 1.1,
      lipides_g: 0.2,
      glucides_g: 7.1,
      fibres_g: 1.4,
      sel_g: 0.01,
      eau_g: 89,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20110",
    nom_fr: "Ail, cru",
    nom_en: "Garlic, raw",
    groupe: "Aromates",
    sous_groupe: "Légumes bulbes",
    nutrition_100g: {
      energie_kcal: 131,
      proteines_g: 5.3,
      lipides_g: 0.4,
      glucides_g: 24.0,
      fibres_g: 3.2,
      sel_g: 0.02,
      eau_g: 64,
    },
    compatible_chylo: true,
    index_glycemique: 30,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "20120",
    nom_fr: "Échalote, crue",
    nom_en: "Shallot, raw",
    groupe: "Aromates",
    sous_groupe: "Légumes bulbes",
    nutrition_100g: {
      energie_kcal: 72,
      proteines_g: 2.5,
      lipides_g: 0.1,
      glucides_g: 14.4,
      fibres_g: 3.2,
      sel_g: 0.01,
      eau_g: 79,
    },
    compatible_chylo: true,
    index_glycemique: 15,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },

  // ========== FRUITS (15) ==========
  {
    code_ciqual: "13001",
    nom_fr: "Pomme, crue",
    nom_en: "Apple, raw",
    groupe: "Fruits",
    sous_groupe: "Fruits à pépins",
    nutrition_100g: {
      energie_kcal: 52,
      proteines_g: 0.3,
      lipides_g: 0.3,
      glucides_g: 11.6,
      fibres_g: 2.3,
      sel_g: 0.01,
      eau_g: 85,
      vitamine_c_mg: 5,
    },
    compatible_chylo: true,
    index_glycemique: 38,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["AUTOMNE", "HIVER"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "13010",
    nom_fr: "Banane, crue",
    nom_en: "Banana, raw",
    groupe: "Fruits",
    sous_groupe: "Fruits exotiques",
    nutrition_100g: {
      energie_kcal: 90,
      proteines_g: 1.1,
      lipides_g: 0.3,
      glucides_g: 20.0,
      fibres_g: 2.6,
      sel_g: 0.01,
      eau_g: 75,
      potassium_mg: 360,
    },
    compatible_chylo: true,
    index_glycemique: 52,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "13020",
    nom_fr: "Orange, crue",
    nom_en: "Orange, raw",
    groupe: "Fruits",
    sous_groupe: "Agrumes",
    nutrition_100g: {
      energie_kcal: 45,
      proteines_g: 0.9,
      lipides_g: 0.2,
      glucides_g: 8.9,
      fibres_g: 2.2,
      sel_g: 0.01,
      eau_g: 87,
      vitamine_c_mg: 53,
    },
    compatible_chylo: true,
    index_glycemique: 42,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["HIVER"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "13030",
    nom_fr: "Kiwi, cru",
    nom_en: "Kiwi, raw",
    groupe: "Fruits",
    sous_groupe: "Fruits exotiques",
    nutrition_100g: {
      energie_kcal: 58,
      proteines_g: 1.1,
      lipides_g: 0.5,
      glucides_g: 10.6,
      fibres_g: 2.7,
      sel_g: 0.01,
      eau_g: 84,
      vitamine_c_mg: 93,
    },
    compatible_chylo: true,
    index_glycemique: 53,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["HIVER"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "13040",
    nom_fr: "Fraise, crue",
    nom_en: "Strawberry, raw",
    groupe: "Fruits",
    sous_groupe: "Fruits rouges",
    nutrition_100g: {
      energie_kcal: 33,
      proteines_g: 0.7,
      lipides_g: 0.4,
      glucides_g: 5.5,
      fibres_g: 2.2,
      sel_g: 0.01,
      eau_g: 90,
      vitamine_c_mg: 60,
    },
    compatible_chylo: true,
    index_glycemique: 40,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["PRINTEMPS", "ETE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "13050",
    nom_fr: "Framboise, crue",
    nom_en: "Raspberry, raw",
    groupe: "Fruits",
    sous_groupe: "Fruits rouges",
    nutrition_100g: {
      energie_kcal: 36,
      proteines_g: 1.2,
      lipides_g: 0.3,
      glucides_g: 4.8,
      fibres_g: 6.7,
      sel_g: 0.01,
      eau_g: 86,
      vitamine_c_mg: 26,
    },
    compatible_chylo: true,
    index_glycemique: 26,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["ETE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "13060",
    nom_fr: "Myrtille, crue",
    nom_en: "Blueberry, raw",
    groupe: "Fruits",
    sous_groupe: "Fruits rouges",
    nutrition_100g: {
      energie_kcal: 57,
      proteines_g: 0.7,
      lipides_g: 0.3,
      glucides_g: 10.0,
      fibres_g: 2.4,
      sel_g: 0.01,
      eau_g: 84,
    },
    compatible_chylo: true,
    index_glycemique: 53,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["ETE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "13070",
    nom_fr: "Pêche, crue",
    nom_en: "Peach, raw",
    groupe: "Fruits",
    sous_groupe: "Fruits à noyau",
    nutrition_100g: {
      energie_kcal: 39,
      proteines_g: 0.9,
      lipides_g: 0.3,
      glucides_g: 8.0,
      fibres_g: 1.5,
      sel_g: 0.01,
      eau_g: 89,
    },
    compatible_chylo: true,
    index_glycemique: 42,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["ETE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "13080",
    nom_fr: "Melon, cru",
    nom_en: "Melon, raw",
    groupe: "Fruits",
    sous_groupe: "Fruits d'été",
    nutrition_100g: {
      energie_kcal: 34,
      proteines_g: 0.8,
      lipides_g: 0.2,
      glucides_g: 6.5,
      fibres_g: 0.9,
      sel_g: 0.01,
      eau_g: 90,
      vitamine_a_µg: 169,
    },
    compatible_chylo: true,
    index_glycemique: 67,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["ETE"],
    source: "CIQUAL",
  },

  // ========== PRODUITS LAITIERS (8) ==========
  {
    code_ciqual: "19001",
    nom_fr: "Yaourt nature 0% MG",
    nom_en: "Plain yogurt 0% fat",
    groupe: "Produits laitiers",
    sous_groupe: "Yaourts",
    nutrition_100g: {
      energie_kcal: 44,
      proteines_g: 4.3,
      lipides_g: 0.1,
      glucides_g: 6.3,
      fibres_g: 0,
      sel_g: 0.1,
      eau_g: 88,
      calcium_mg: 142,
    },
    compatible_chylo: true,
    index_glycemique: 35,
    allergenes: ["lactose"],
    regime_exclusions: ["VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "19002",
    nom_fr: "Yaourt grec 0% MG",
    nom_en: "Greek yogurt 0% fat",
    groupe: "Produits laitiers",
    sous_groupe: "Yaourts",
    nutrition_100g: {
      energie_kcal: 59,
      proteines_g: 10.2,
      lipides_g: 0.4,
      glucides_g: 3.6,
      fibres_g: 0,
      sel_g: 0.05,
      eau_g: 85,
      calcium_mg: 110,
    },
    compatible_chylo: true,
    index_glycemique: 11,
    allergenes: ["lactose"],
    regime_exclusions: ["VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "19010",
    nom_fr: "Fromage blanc 0% MG",
    nom_en: "Cottage cheese 0% fat",
    groupe: "Produits laitiers",
    sous_groupe: "Fromages frais",
    nutrition_100g: {
      energie_kcal: 46,
      proteines_g: 7.5,
      lipides_g: 0.2,
      glucides_g: 4.0,
      fibres_g: 0,
      sel_g: 0.1,
      eau_g: 87,
      calcium_mg: 103,
    },
    compatible_chylo: true,
    index_glycemique: 27,
    allergenes: ["lactose"],
    regime_exclusions: ["VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "19020",
    nom_fr: "Lait écrémé",
    nom_en: "Skimmed milk",
    groupe: "Produits laitiers",
    sous_groupe: "Laits",
    nutrition_100g: {
      energie_kcal: 35,
      proteines_g: 3.4,
      lipides_g: 0.2,
      glucides_g: 5.0,
      fibres_g: 0,
      sel_g: 0.1,
      eau_g: 90,
      calcium_mg: 125,
    },
    compatible_chylo: true,
    index_glycemique: 30,
    allergenes: ["lactose"],
    regime_exclusions: ["VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },

  // ========== AUTRES (5) ==========
  {
    code_ciqual: "36000",
    nom_fr: "Œuf entier, cuit",
    nom_en: "Whole egg, cooked",
    groupe: "Protéines",
    sous_groupe: "Œufs",
    nutrition_100g: {
      energie_kcal: 134,
      proteines_g: 12.6,
      lipides_g: 9.0,
      glucides_g: 0.6,
      fibres_g: 0,
      sel_g: 0.3,
      eau_g: 76,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["œuf"],
    regime_exclusions: ["VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "36001",
    nom_fr: "Blanc d'œuf, cuit",
    nom_en: "Egg white, cooked",
    groupe: "Protéines",
    sous_groupe: "Œufs",
    nutrition_100g: {
      energie_kcal: 52,
      proteines_g: 10.9,
      lipides_g: 0.2,
      glucides_g: 0.7,
      fibres_g: 0,
      sel_g: 0.4,
      eau_g: 87,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: ["œuf"],
    regime_exclusions: ["VEGAN"],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
  },
  {
    code_ciqual: "17000",
    nom_fr: "Huile d'olive",
    nom_en: "Olive oil",
    groupe: "Huiles et matières grasses",
    sous_groupe: "Huiles végétales",
    nutrition_100g: {
      energie_kcal: 899,
      proteines_g: 0,
      lipides_g: 99.9,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0,
      eau_g: 0,
    },
    compatible_chylo: false,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
    notes: "Lipides très élevés - usage modéré uniquement",
  },
  {
    code_ciqual: "17010",
    nom_fr: "Huile de coco MCT",
    nom_en: "MCT coconut oil",
    groupe: "Huiles et matières grasses",
    sous_groupe: "Huiles végétales",
    nutrition_100g: {
      energie_kcal: 862,
      proteines_g: 0,
      lipides_g: 99.0,
      glucides_g: 0,
      fibres_g: 0,
      sel_g: 0,
      eau_g: 0,
    },
    compatible_chylo: true,
    index_glycemique: 0,
    allergenes: [],
    regime_exclusions: [],
    saisons: ["TOUTE_ANNEE"],
    source: "CIQUAL",
    notes: "MCT tolérés en chylomicronémie - usage modéré",
  },
];
